import { DefaultTheme } from 'styled-components';
export const lightTheme = {
  colors: {
    globalBackground: '#ffffff',
    toDo: '#4F46E5',
    inProgress: '#F59E0B',
    done: '#22C55E',
    boardHeaderBack: '#f8fafc',
    boardTitle: '#1e293b',
    textSecondary: '#475569',
    border: '#94a3b8',
    borderHover: '#94a3b8',
    primary: '#4f46e5',
    primaryHover: '#4338ca',
    secondary: '#f1f5f9',
    secondaryHover: '#e2e8f0',
    formBackground: '#ffffff',
    inputBorder: '#e2e8f0',
    inputFocusBorder: '#94a3b8',
    inputFocusShadow: 'rgba(79, 70, 229, 0.2)',
    buttonText: '#ffffff',
    formText: '#333',
    formTitle: '#333',
    danger: '#ef4444',
    dangerHover: '#dc2626',
    success: '#2563eb',
    successHover: '#1d4ed8',
    priorityBg: '#eef2ff',
    selectArrow: '#000000',
    selectFocus: '#c7d2fe',
    placeholder: '#1e293b',
    columnBackground: '#f8fafc',
    deleteButton: '#666',
    deleteButtonHover: '#ff0000',
    taskCounterBg: '#ffffff',
    addTaskButtonHover: 'transparent',
    inputBackground: 'white',
    priorityHighBg: '#FFEBEE',
    priorityHighText: '#C62828',
    priorityMediumBg: '#FFF8E1',
    priorityMediumText: '#F57F17',
    priorityLowBg: '#E8F5E9',
    priorityLowText: '#2E7D32',
    taskCardBackground: 'white',
    taskTitle: '#1e293b',
    taskDescription: '#475569',
    saveButton: '#4caf50',
    saveButtonHover: '#45a049',
    deleteButtonDanger: 'rgb(187, 39, 6)',
    deleteButtonDangerHover: 'rgba(187, 39, 6, 0.67)',
  },
  sizes: {
    gridColumnWidth: '250px',
    padding: {
      boardContainer: '24px',
      boardHeader: '35px',
      form: '16px',
      button: '8px 16px',
      input: '10px 12px',
    },
    gap: '16px',
    borderRadius: {
      small: '6px',
      medium: '8px',
      large: '12px',
      circle: '50%',
    },
    icon: {
      small: '18px',
      medium: '20px',
    },
    form: {
      gapSmall: '4px',
      gapMedium: '8px',
      borderRadiusFull: '1234px',
    },
    column: {
      width: '280px',
      padding: '16px',
      margin: '16px',
      borderRadius: '32px',
    },
    title: {
      borderRadius: '9999px',
      padding: '8px 12px',
    },
    taskCounter: {
      width: '33px',
      height: '32px',
      borderRadius: '1234px',
    },
    taskCard: {
      borderRadius: '24px',
      padding: '12px',
      marginBottom: '12px',
    },
    priorityLabel: {
      padding: '4px 8px',
      borderRadius: '1234px',
      marginBottom: '8px',
    },
    editForm: {
      padding: '12px',
      borderRadius: '24px',
      gap: '16px',
    },
    input: {
      padding: '8px 12px',
      borderRadius: '4px',
    },
    textarea: {
      minHeight: '80px',
    },
    select: {
      width: '120px',
    },
  },
  breakpoints: {
    mobile: '760px',
    tablet: '980px',
    laptop: '1200px',
    desktop: '1600px',
    large: '1920px',
  },
  typography: {
    boardTitle: {
      fontSize: '30px',
      fontWeight: 800,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
    tittle: {
      fontWeight: 700,
    },
    button: {
      fontSize: '14px',
      fontWeight: 600,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
    input: {
      fontSize: '14px',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
    label: {
      fontSize: '14px',
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
    formTitle: {
      fontSize: '14px',
      fontWeight: 600,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
    formText: {
      fontSize: '16px',
      fontWeight: 400,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
  },
  shadows: {
    small: '0 2px 4px rgba(0, 0, 0, 0.1)',
    medium: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  transitions: {
    default: 'all 0.2s',
  },
} as DefaultTheme;

export const darkTheme = {
  ...lightTheme,
  colors: {
    ...lightTheme.colors,
    boardHeaderBack: '#1a1a2e',
    boardTitle: '#ffffff',
    textSecondary: '#a8a8a8',
    formBackground: '#16213e',
    formTitle: '#ffffff',
    columnBackground: '#1a1a2e',
    taskCardBackground: '#16213e',
    taskTitle: '#ffffff',
    taskDescription: '#e6e6e6',
    inputBackground: '#0f3460',
    inputBorder: '#2d3748',
    placeholder: '#a0aec0',
    globalBackground: '#121212',
  },
} as DefaultTheme;

export type ThemeColors = typeof lightTheme.colors;
